const Data1 = [
  {
    id: '1',
    title: 'PROGRAMMING GAME UNITY 3D',
    category: 'Most recent',
    price: '$200',
    img: 'https://khoapham.vn/public/images/logo/unity.png',
    desc: 'Build Cross-Platform Games (Web, PC, Mobile) with Unity...',
    View: 'VIEW DETAIL',
    Student: '25',
  },
  {
    id: '2',
    title: 'PROGRAMMING ANDROID',
    category: 'Most view',
    price: '$140',
    img: 'https://khoapham.vn/public/images/logo/android.png',
    desc: 'Providing all Android programming knowledge from A-Z will help you confidently in the Android Programming profession',
    View: 'VIEW DETAIL',
    Student: '35',
  },
  {
    id: '3',
    title: 'PROGRAMMING FLUTTER',
    category: 'Most popular',
    price: '$150',
    img: 'https://khoapham.vn/public/images/logo/flutter.jpg',
    desc: 'Flutter was developed to solve common problems in mobile, Fast Development and Native Performance.',
    View: 'VIEW DETAIL',
    Student: '30',
  },
  {
    id: '4',
    title: 'PROGRAMMING NODEJS',
    category: 'Most popular',
    price: '$100',
    img: 'https://khoapham.vn/public/images/logo/nodejs.png',
    desc: 'NodeJS is an open source, used to build network applications, especially applications that require real time and large request volume.',
    View: 'VIEW DETAIL',
    Student: '22',
  },
  {
    id: '5',
    title: 'PROGRAMMING PHP',
    category: 'The cheapest',
    price: '$30',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/4.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '21',
  },
  {
    id: '6',
    title: 'Paneer Aachari',
    category: 'Most recent',
    price: '$40',
    img: 'https://edumall.vn/_next/image?url=%2Fapi%2Fimageproxy%3Furl%3Dhttps%253A%252F%252Fcdn2.topica.vn%252F191ab4fd-9c62-4494-b209-51f86a3924d3%252Fproduct%252F613c8cf0e818b400255e3d77&w=1920&q=50',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '40',
  },
  {
    id: '7',
    title: 'High-Dimensional Data Analysis',
    category: 'Most recent',
    price: '$50',
    img: 'https://edumall.vn/_next/image?url=%2Fapi%2Fimageproxy%3Furl%3Dhttps%253A%252F%252Fcdn2.topica.vn%252F191ab4fd-9c62-4494-b209-51f86a3924d3%252Fproduct%252F613c24dde818b400255e39a1&w=1920&q=50',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '30',
  },
  {
    id: '8',
    title: 'Astronomia Virtual',
    category: 'Most recent',
    price: '$60',
    img: 'https://khoapham.vn/public/images/logo/forex.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '33',
  },
  {
    id: '9',
    title: 'PROGRAMMING HTML5',
    category: 'Most view',
    price: '$55',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/7.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '40',
  },
  {
    id: '10',
    title: 'BASIC FOREX COURSE & BINARY OPTIONS',
    category: 'Most view',
    price: '$45',
    img: 'https://khoapham.vn/public/images/logo/mean.png',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '15',
  },
]

export default Data1
