const Data = [
  {
    id: '1',
    title: 'Astronomia Virtual',
    category: 'Most recent',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$150',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/4.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '20',
  },
  {
    id: '2',
    title: 'AP Physics 1',
    category: 'Most view',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$102',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/5.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '30',
  },
  {
    id: '3',
    title: 'The Einstein Revolution',
    category: 'Latest',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$130',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/7.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '40',
  },
  {
    id: '4',
    title: 'Astrophysics: Cosmology',
    category: 'most popular',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$100',
    img: 'https://prod-discovery.edx-cdn.org/media/course/image/b711f246-fb5a-4933-afbc-b69d00e5bd57-d969b201b05a.jpg',
    desc: 'Detail course online.',
    View: 'VIEW DETAIL',
    Student: '25',
  },
  {
    id: '5',
    title: 'Introduction to Water and Climate',
    category: 'The cheapest',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$200',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/4.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '35',
  },
  {
    id: '6',
    title: 'Solar Energy: Photovoltaic(PV) Technologies',
    category: 'Most recent',
    Skill: 'Web Development, Front-End Web Development, Computer...',
    price: '$120',
    img: 'https://prod-discovery.edx-cdn.org/media/course/image/c363944c-5adb-4490-b8f9-2b9b77be2952-956f581b8aa1.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '45',
  },
  {
    id: '7',
    title: 'Plasma Physics: Introduction',
    category: 'Most recent',
    price: '$150',
    img: 'https://prod-discovery.edx-cdn.org/media/course/image/e351fadb-a1ce-4fc2-80ba-1114c38ca432-ee9ab62256c2.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '15',
  },
  {
    id: '8',
    title: 'Semiconductors for Beginners',
    category: 'Most recent',
    price: '$105',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/8.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '40',
  },
  {
    id: '9',
    title: 'Solar Energy: From Fundamentals',
    category: 'Most view',
    price: '$130',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/6.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '25',
  },
  {
    id: '10',
    title: 'Fundamentals of Biomedical Imaging: Magnetic Resonance',
    category: 'Most view',
    price: '$140',
    img: 'https://kodesolution.com/html/2016/studypress-html/demo/images/project/7.jpg',
    desc: 'Detail course online',
    View: 'VIEW DETAIL',
    Student: '20',
  },
]

export default Data
